# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Zerocracy
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/ruby
assets:
  docker-password: yegor256/home#assets/docker-password
merge:
  script: |-
    sudo make -C "$(pwd)"
release:
  pre: false
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    sed -i -e "s/0.0.0/${tag}/" entry.sh
    sed -i -e "s/judges-action:latest/judges-action:${tag}/" action.yml
    sed -i -e "s/0.0.0/${tag}/" Dockerfile
    git add entry.sh
    git add action.yml
    git add Dockerfile
    git commit -m "version set to ${tag}"
    repo=yegor256/judges-action
    sudo make -C "$(pwd)"
    sudo docker build "$(pwd)" --tag "${repo}:${tag}"
    sudo docker build "$(pwd)" --tag "${repo}:latest"
    cat ../docker-password | sudo docker login --password-stdin -u yegor256
    sudo docker push "${repo}:${tag}"
    sudo docker push "${repo}:latest"
