# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Zerocracy
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: zerocracy
'on':
  schedule:
    - cron: '0,30 * * * *'
concurrency:
  group: zerocracy
  cancel-in-progress: false
jobs:
  zerocracy:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: zerocracy/judges-action@0.7.0
        with:
          token: ${{ secrets.ZEROCRACY_TOKEN }}
          verbose: false
          github_token: ${{ secrets.PAT }}
          repositories: yegor256/judges,yegor256/factbase,zerocracy/*
          factbase: zerocracy.fb
          cycles: 3
      - uses: zerocracy/pages-action@0.0.48
        with:
          options: |
            github_token=${{ secrets.PAT }}
          verbose: true
          factbase: zerocracy.fb
          output: pages
      - uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          folder: pages
          clean: false
