# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Zerocracy
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: zerocracy
'on':
  schedule:
    - cron: '0,30 * * * *'
concurrency:
  group: zerocracy
  cancel-in-progress: false
permissions:
  contents: write
jobs:
  zerocracy:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: zerocracy/judges-action@0.14.15
        with:
          token: ${{ secrets.ZEROCRACY_TOKEN }}
          github-token: ${{ secrets.PAT }}
          repositories: yegor256/judges,yegor256/factbase,zerocracy/*,yegor256/0rsk
          factbase: zerocracy.fb
          options: |
            sqlite_cache_maxsize=50Mb
            sqlite_cache_maxvsize=100Kb
      - uses: zerocracy/pages-action@0.2.0
        with:
          verbose: true
          github-token: ${{ secrets.PAT }}
          factbase: zerocracy.fb
          output: pages
      - uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          folder: pages
          clean: false
